### PR TITLE
DEP Set PHP 7.4 as the minimum version

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-framework/issues/10219

### CODE REVIEW

**Review by maxime-rainville — COMMENTED** [review]
Build is failing but it seems unrelated to this change. I just restarted the build just to double check it's not gobblins

**Comment by emteknetnz** [comment]
Attempting to fix the broken behat test in admin with this PR https://github.com/silverstripe/silverstripe-admin/pull/1290

**Comment by maxime-rainville** [comment]
Behat is grumpy for some reason

**Comment by emteknetnz** [comment]
@maxime-rainville behat issue is pre-existing

**Comment by maxime-rainville** [comment]
Merged. We'll aim to fix the behat issue independantly

**Comment by maxime-rainville** [comment]
Hit the wrong button!

**Review by maxime-rainville — APPROVED** [review]
Approve despite broken build. We'll fix interdependently.

**Pull request merged**
