### PR TITLE
NEW Add MFA module with TOTP method (fixes #280)

### LINKED ISSUE #280: Incude MFA module in new projects via installer
The upcoming 4.6 release already includes `silverstripe/loginforms` via the installer. This way we can ensure the functionality finds its way into new projects, without causing disruption in existing projects (through an inclusion in recipes). I think we should do the same with the `silverstripe/mfa` and `silverstripe/totp-authenticator` modules. According to the [MFA module readme](https://github.com/silverstripe/silverstripe-mfa), this should result in TOTP being enabled by default, but optional for users. The aim here is to provide *more security choices by default for users*. Adding MFA to new projects is close to pointless if it relies on a CMS admin caring enough about this problem space to enable the feature through a checkbox somewhere. Instead, CMS admins should be empowered to disable MFA, or require it. But the right defaults need to be in place without this interaction.

`silverstripe/webauthn-authenticator` should not be installed by default due to complexities around copying logins between environments, multi-domain usage, etc. 

When doing this, we should also update docs in https://docs.silverstripe.org/en/4/developer_guides/security/

Since we've already released 4.6.0-beta1 of the installer, this would need to be targeted at 4.7.0.

This is a very similar discussion to the [inclusion in the cwp/installer](https://github.com/silverstripe/cwp/issues/258).

### PR DESCRIPTION
**Pull request by chillu**

### CODE REVIEW

**Comment by chillu** [comment]
Fixed conflict, used `-dev` dependency convention from other bits of the composer.json.
This is currently blocked by some concerns at https://github.com/silverstripe/silverstripe-installer/issues/280

**Comment by emteknetnz** [comment]
Failing unit test, I'm not sure off the top of my head what's causing this
image

**Comment by brynwhyman** [comment]
Should this PR just be closed for now? It's going to need more work based off the conversation in #280

**Comment by chillu** [comment]
Yep, closing - needs more work around token generation

**Pull request closed without merging**
