### PR TITLE
Added phpunit to dev dependencies

### PR DESCRIPTION
**Pull request by assertchris**

### CODE REVIEW

**Comment by dhensby** [comment]
Personally, I think this makes sense.

But given these comments https://github.com/silverstripe/silverstripe-framework/pull/3104#issuecomment-42606995 there is a reason that it isn't currently included.

@silverstripe/core-team any new thoughts on this?

**Comment by dhensby** [comment]
PS: we only need this once and can merge it up into the other branches ourselves if needed

**Comment by assertchris** [comment]
Just wanted to avoid any hassles by making one for each major/minor... :)

**Comment by tractorcow** [comment]
2.4 is still a think? I thought I deleted that branch. Oh well. :)

**Comment by dhensby** [comment]
@assertchris appreciated, thanks. I just wanted to save YOU the hassle!

**Comment by assertchris** [comment]
@dhensby it's no trouble. Happy to help!

**Comment by chillu** [comment]
I've agreed with this changed a year ago in https://github.com/silverstripe/silverstripe-framework/pull/3104#issuecomment-42632741 (just reminding myself mostly hehe).

What do you guys think about using `composer create-project --no-dev` on http://www.silverstripe.org/software/download/? My concern is that the first experience for users is now slowed down even more by composer pulling down dev dependencies which first time installers are unlikely to use.

**Comment by stevie-mayhew** [comment]
@chillu I would even go as far as to recommend `composer create-project --no-dev --prefer-dist`

**Comment by dhensby** [comment]
I think there's a trade off between getting someone's initial project creation / dev environment running in a way that we reduce friction to writing and executing tests and getting it set up as quickly as possible.

If we explain what the flags are for and why as well as directing people to the docs for creating a project for SS patches, then we can instruct them however we like, I suppose.

I agree that the provided package on the dowload page should not be including dev deps.

**Comment by chillu** [comment]
@tractorcow @camfindlay @unclecheese Would you be able to check out the `create-project` suggestion above, and determine if we can add it to silverstripe.org/download? I've timed it on my ~10Mbit connection at home (with an `rm -rf ~/.composer/cache`), and its 30% slower since this change has been merged in (using `3.1.x-dev` with `--prefer-dist` to emulate checking out a tag).

Before:

```
time composer create-project --no-dev --prefer-dist silverstripe/installer project2 3.1.x-dev
Installing silverstripe/installer (3.1.x-dev 38ee2f9a1d91feb6e2506c85958328930906eee8)
  - Installing silverstripe/installer (3.1.x-dev 38ee2f9)
    Downloading: 100%

Created project in project2
Loading composer repositories with package information
Installing dependencies
  - Installing composer/installers (dev-master d64e23f)
    Downloading: 100%

  - Installing silverstripe/framework (3.1.x-dev 773624a)
    Downloading: 100%

  - Installing silverstripe/cms (3.1.x-dev c7814cf)
    Downloading: 100%

  - Installing silverstripe-themes/simple (dev-master 63c549e)
    Downloading: 100%

Writing lock file
Generating autoload files

real	2m27.034s
user	0m3.414s
sys	0m2.110s
```

After:

```
time composer create-project --prefer-dist silverstripe/installer project1 3.1.x-dev
Installing silverstripe/installer (3.1.x-dev 38ee2f9a1d91feb6e2506c85958328930906eee8)
  - Installing silverstripe/installer (3.1.x-dev 38ee2f9)
    Downloading: 100%

Created project in project1
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing composer/installers (dev-master d64e23f)
    Downloading: 100%

  - Installing silverstripe/framework (3.1.x-dev 773624a)
     Downloading: 100%

  - Installing silverstripe/cms (3.1.x-dev c7814cf)
    Downloading: 100%

  - Installing silverstripe-themes/simple (dev-master 63c549e)
    Downloading: 100%

  - Installing symfony/yaml (2.7.x-dev d04b392)
    Downloading: 100%

  - Installing phpunit/php-text-template (1.2.0)
    Downloading: 100%

  - Installing phpunit/phpunit-mock-objects (1.2.x-dev c39c451)
    Downloading: 100%

  - Installing phpunit/php-timer (1.0.5)
    Downloading: 100%

  - Installing phpunit/php-token-stream (1.2.2)
    Downloading: 100%

  - Installing phpunit/php-file-iterator (1.3.4)
    Downloading: 100%

  - Installing phpunit/php-code-coverage (1.2.x-dev fe24668)
    Downloading: 100%

  - Installing phpunit/phpunit (3.7.38)
    Downloading: 100%

phpunit/php-code-coverage suggests installing ext-xdebug (>=2.0.5)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files

real	3m24.262s
user	0m5.368s
sys	0m2.562s
```

**Comment by camfindlay** [comment]
I think it would be good to have less to install to start with so would be happy adding the --no-dev flag etc to the download page as long as someone can update the installation documentation to explain why and what happens if you omit these flags. Get those docs in first and I'll make arrangements to update silverstripe.org content to match. 

Do we have numbers on improvements if --prefer-dist is included too. Need to balance keeping it simple with keeping it speedy. (Anyone know what other composer frameworks say on first install?).

**Comment by assertchris** [comment]
@camfindlay you say "other composer frameworks" like this is one...

:trollface:

**Comment by camfindlay** [comment]
I mean, what do other frameworks that use composer mention in their docs when it comes to installation via composer? We want newcomers to get into using composer, we also don't want to scare them away so we should provide good information :)

**Comment by camfindlay** [comment]
Fyi, the slowness of composer installing SilverStripe regularly comes up whenever I've run training courses. (Still, it's faster then manually dealing with dependancies!). @assertchris what's your position on this? Should a new dev always get dev tools by default or should they be introduced to them so they know what they're getting and can make the choice to run a composer update to get them after initial install?

**Comment by camfindlay** [comment]
I can confirm a good minute+ improvement using @chillu 's method above:

Before:

```
time composer create-project --prefer-dist silverstripe/installer project1 3.1.x-dev
Installing silverstripe/installer (3.1.x-dev 38ee2f9a1d91feb6e2506c85958328930906eee8)
  - Installing silverstripe/installer (3.1.x-dev 38ee2f9)
    Downloading: 100%         

Created project in project1
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing composer/installers (dev-master d64e23f)
    Downloading: 100%         

  - Installing silverstripe/framework (3.1.x-dev 773624a)
    Downloading: 100%         

  - Installing silverstripe/cms (3.1.x-dev c7814cf)
    Downloading: 100%         

  - Installing silverstripe-themes/simple (dev-master 63c549e)
    Downloading: 100%         

  - Installing symfony/yaml (2.7.x-dev d04b392)
    Downloading: 100%         

  - Installing phpunit/php-text-template (1.2.0)
    Downloading: 100%         

  - Installing phpunit/phpunit-mock-objects (1.2.x-dev c39c451)
    Downloading: 100%         

  - Installing phpunit/php-timer (1.0.5)
    Downloading: 100%         

  - Installing phpunit/php-token-stream (1.2.2)
    Downloading: 100%         

  - Installing phpunit/php-file-iterator (1.3.4)
    Downloading: 100%         

  - Installing phpunit/php-code-coverage (1.2.x-dev fe24668)
    Downloading: 100%         

  - Installing phpunit/phpunit (3.7.38)
    Downloading: 100%         

phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files

real	4m29.561s
user	0m8.136s
sys	0m2.691s
```

After:

```
time composer create-project --no-dev --prefer-dist silverstripe/installer project2 3.1.x-dev
Installing silverstripe/installer (3.1.x-dev 38ee2f9a1d91feb6e2506c85958328930906eee8)
  - Installing silverstripe/installer (3.1.x-dev 38ee2f9)
    Downloading: 100%         

Created project in project2
Loading composer repositories with package information
Installing dependencies
  - Installing composer/installers (dev-master d64e23f)
    Downloading: 100%         

  - Installing silverstripe/framework (3.1.x-dev 773624a)
    Downloading: 100%         

  - Installing silverstripe/cms (3.1.x-dev c7814cf)
    Downloading: 100%         

  - Installing silverstripe-themes/simple (dev-master 63c549e)
    Downloading: 100%         

Writing lock file
Generating autoload files

real	3m6.989s
user	0m4.008s
sys	0m1.940s
```

Guess the key question here is... is it worth a minute of time to ensure a dev has dev tools installed? (and how many minutes might it be on a lesser computer?)

**Comment by assertchris** [comment]
@camfindlay there are different concerns at play. New "users" don't need the extra install time. New "contributors" need to be able to test quickly. 

Having just spent time setting up my first SS framework contribution environment (I still can't run phpunit against upstream/3) I have some first-hand experience with how difficult it is for new "contributors" to start.

So I think you're on the money about documenting the differences on /download. But I also feel like it shouldn't be _this_ hard to contribute (which, for non-trivial contribution, means being able to test easily)...

**Comment by camfindlay** [comment]
@assertchris yip agree getting set up to contribute should be simple. 

So are we in agreement that the default copy/paste composer command on the /downloads page of silverstripe.org should include the --no-dev flag and we should make mention in the docs about what to do next if you want to get the dev tools?

**Comment by camfindlay** [comment]
Also just for fun and statistics... I'm running the documented composer create-projects of a couple of other frameworks to get a comparative time to getting all the things vs SilverStripe things. Post the results shortly.

**Comment by camfindlay** [comment]
```
time composer create-project symfony/framework-standard-edition my_project_name
...
real	5m15.348s
user	0m7.475s
sys	0m3.479s
```

and

```
time composer create-project laravel/laravel your-project-name --prefer-dist
...
real	7m43.518s
user	0m24.825s
sys	0m3.512s
```

So actually even including our dev tools we are still pretty fast in comparison 

I also wonder whether we should change the /path/to/project in that copy and paste on the download page so that it is actually a pure copy/paste process?

**Comment by assertchris** [comment]
@camfindlay Our project is slow because there's lots to download. Others are slow because there's a big dependency graph to work out. 

It doesn't make much difference except that modular structure is quantifiably better. Different thread though...

**Pull request merged**
