### PR TITLE
BUG Fix basic auth breaking sites on mod_php

### LINKED ISSUE #79: Revert #78
This causes all http requests (on mod_php) to only work through index.php. Removing index.php breaks the site.

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #79 
Instead of reverting the commit, simply make it not break subsequent rules. :)

### CODE REVIEW

**Comment by dhensby** [comment]
Ok, shall we get this in?

**Comment by tractorcow** [comment]
It would be great to get @cjsewell to test this works, since he raised https://github.com/silverstripe/silverstripe-installer/pull/78 originally. If we can't merge this is time for 3.1.9 (which will be SOON) I'll have to revert the commit directly.

**Comment by tractorcow** [comment]
If you have php running in CGI then feel free to double check in his place that it works. :)

**Comment by cjsewell** [comment]
Sorry about the lack of input lately ( holiday season! )

I will setup a few instances under mod_apache and CGI + FPM and will let you know how it goes.

**Comment by tractorcow** [comment]
https://github.com/silverstripe/silverstripe-framework/issues/3794 also needs to be checked... something's gone wrong there too. =(

**Comment by cjsewell** [comment]
Should finally be fixed in PR https://github.com/silverstripe/silverstripe-installer/pull/81

Tested in Apache 2.2 with mod_php, fastcgi and phpfpm

**Comment by tractorcow** [comment]
Closed in favour of #81

**Pull request closed without merging**
