### PR TITLE
Adjust behat timeout for asset-admin tests

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes https://github.com/silverstripe/silverstripe-installer/issues/192

### CODE REVIEW

**Comment by flamerohr** [comment]
Worth a try

**Comment by tractorcow** [comment]
I can't figure out why imagick is failing; Locally and on the silverstripe/assets repo it passes fine.

Maybe because we need to upgrade off dist: precise?

**Comment by dhensby** [comment]
imagick seems fine now - just behat tests failing

**Comment by tractorcow** [comment]
Yeah, it's still on precise; I'll give it the same magic we did for framework and fix firefox tag.

**Comment by dhensby** [comment]
*magic*

**Comment by tractorcow** [comment]
Pushed up an update to `.travis.yml`

**Comment by tractorcow** [comment]
Finally green!

**Pull request merged**
