### PR TITLE
DEP 4.10 requirements

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripeltd/product-issues/issues/492

### CODE REVIEW

**Review by maxime-rainville — APPROVED** [review]
LGTM

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
Shouldn't [travis require recipe-testing 2](https://github.com/creative-commoners/silverstripe-installer/blob/pulls/4/410/.travis.yml#L8)?

**Comment by emteknetnz** [comment]
> Shouldn't travis require recipe-testing 2?
Eventually (maybe now?) currently travis-shared does some feature detection to see if you're using phpunit9, and if so, updates the requirement to recipe-testing:^2 - https://github.com/silverstripe/silverstripe-travis-shared/blob/master/config/base.yml#L83

This was done pre merging all those phpunit9 PR's so we needed to support both phpunit 5 + 9.  Now phpunit 5 is only relevant for existing PR's targeting 4.9 and such

**Comment by emteknetnz** [comment]
Updated

**Review by maxime-rainville — APPROVED** [review]
LGTM

**Pull request merged**
