### PR TITLE
Additions to gitignore

### PR DESCRIPTION
**Pull request by gregsmirnov**
I propose 2 additions to .gitignore

1. add SilverStripe modules (they are external like /vendor/)
2. add a note how to create global gitignore file. It specifies that environment excludes should not be a part of this file and gives a hint how to handle them.

### CODE REVIEW

**Comment by jonom** [comment]
1. Sounds good to me except for `/themes/` - this is a place for site-specific code like `mysite` so you wouldn't want to exclude this. The installer provides the Simple theme as a starting point but it's not a composer dependancy and won't be auto-updated.

2. Not sure if this is super useful as is. If the comment is intended for people who don't know a lot about git they may not know a lot about shell commands either so perhaps should break down a bit further what that command does and where it will place the file (in your user directory), and the fact that exclude patterns in that file will apply to all git repos on your machine. Maybe name it `.gitexcludes` or similar too, so we're not mixing up the concepts of ignore and exclude?

**Comment by dhensby** [comment]
My view is that this isn't appropriate - we shouldn't make these kinds of assumptions (tightly couple to other modules).

Global ignores are fantastic for things like `.DS_Store`, `Thumbs.db` and other OS level ignores - it allows a developer to ignore files system files (and their own IDE's files) without polluting the `.gitignore` of the project.

I'd recommend you look at using this excellent module in your projects instead: https://github.com/guru-digital/SSAutoGitIgnore (it even gets a mention in the docs https://docs.silverstripe.org/en/3.2/getting_started/composer/#installing-and-enabling-the-ssautogitignore-package)

**Comment by jonom** [comment]
@dhensby I think some more discussion is warranted here. This PR doesn't introduce a .gitignore file it only modifies the repo's existing one. Everything in the vendor folder is already ignored by said file so I think it makes sense to be consistent and ignore other composer dependencies as well.

The mention of global excludes might have confused matters here? But it is only a mention - literally a comment in the .gitignore file (which maybe should be removed).

I'm not sure the coupling argument makes sense for this particular repo because it's an opinionated repo meant to set you up with a practical starting point, and the coupling here is only as tight as the composer.json file which declares dependencies.

The module you mentioned is certainly a good idea to have too but I don't think the availability of that module makes this PR invalid.

**Comment by dhensby** [comment]
> I think some more discussion is warranted here

Happy for more discussion, feel free to re-open

Adding this means adding a set of rules that need to be managed every time we update module deps in this repo. There's an automated tool for doing this which is far superior to this approach and would allow not just the modules we add as part of the installer, but also modules that are added by the developer too.

@gregsmirnov are you happy that the automated method achieves the same aim as you PR and, perhaps, exceeds it?

**Comment by jonom** [comment]
True - maybe we should add SSAutoGitIgnore as an Installer dependency instead :D or at least recommend it with [suggest](https://getcomposer.org/doc/04-schema.md#suggest)

**Comment by dhensby** [comment]
The author had suggested adding it to core, but I said that I didn't think it was something we should maintain. 

We could `suggest` it, but I worry we'd have to support it. 

I see this as a stop gap until we get modules in vendor, so wouldn't encourage too much time on it.

**Comment by jonom** [comment]
> The author had suggested adding it to core, but I said that I didn't think it was something we should maintain.

Sorry, I missed wherever that discussion happened - thanks for indulging me!

**Comment by dhensby** [comment]
This was the issue a while back: https://github.com/silverstripe/silverstripe-framework/issues/3967

**Comment by jonom** [comment]
Cheers Dan. I tend to agree with the author's rational that the Installer is a best-practice starting point so adding things to it isn't really the same as adding something to 'core'. I would happily drop the `reports` and `siteconfig` modules for instance and add/maintain `SSAutoGitIgnore` instead as I think it's more useful for majority of sites. But that's an aside, I agree with your reasoning on this PR.

**Comment by gregsmirnov** [comment]
I observed how other developers start new SS project and "Installer is a best-practice starting point".
My reasoning for this PR was that after initial installation (`git clone`, and `composer install`). I have a ready to start git repo. However `git status` told me differently.
Thank you Dan for pointing to SSAutoGitignore module. I missed this update in docs, but will integrate into our repos as `require-dev` dependency.

**Comment by JorisDebonnet** [comment]
I guess this ties into the discussion about whether modules should go in the vendor folder or into a modules subfolder.

In any case, I agree with everything in @jonom's second post, especially about this repo serving as a practical starting point. Having all dependancies that are guaranteed to be installed in .gitignore lowers the chance for mistakes by people that are new to everything (git, composer, frameworks, ..). I just mean, I don't see a good reason _not_ to include them. If maintaining the .gitignore file is the main concern, I'm sure the community will keep it up to date :) If it helps, then only from 4.0 onward.

So yeah, I guess I'm just adding a vote for this :)

(I had made a slightly improved (imo) PR in #126; sorry I had not found this one first)

**Comment by dhensby** [comment]
If the purpose is to help developers not accidentally commit folders into git, then what about when they add new modules that aren't ignored? If they never knew they needed to this because we did it for them, they could still be set up for a fall. Better to have clearer docs, automation and education than solve a problem that only exists before any extra module is added.

> Having all dependancies that are guaranteed to be installed in .gitignore lowers the chance for mistakes by people that are new to everything (git, composer, frameworks, ..)

We can't ever guarantee what the folder names will be so someone would have to be constantly monitoring that these don't change

> If maintaining the .gitignore file is the main concern, I'm sure the community will keep it up to date :)

The problem with claiming the "community" will keep it up to date is that the community is fluid and can't make these long term commitments because we can't get collective consent or responsibility for individual tasks. Ultimately core maintainers have to underwrite any guarantee the community will make.

> If it helps, then only from 4.0 onward.

Hopefully in 4 we won't have modules in the webroot, but let's see.

**Comment by tractorcow** [comment]
It'll be fixed when modules go to vendor :)

**Pull request closed without merging**
