### PR TITLE
BUG Treat login-forms as a core module

### PR DESCRIPTION
**Pull request by maxime-rainville**
Login forms should be treated as a core module. We should be doing new releases of login forms along with our quarterly releases.

### CODE REVIEW

**Comment by emteknetnz** [comment]
@maxime-rainville travis failure is a behat failure

image
https://travis-ci.org/github/silverstripe/silverstripe-installer/jobs/691663320#L1153

Is this related to missing frameworktest 0.1.0?

**Comment by maxime-rainville** [comment]
I restarted the build. Now the behat test are green but 3 other builds are broken.

**Comment by emteknetnz** [comment]
OK no worries, it's this issue https://github.com/silverstripe/silverstripe-assets/issues/406

It has a pull-request that's being peer-reviewed

**Comment by emteknetnz** [comment]
getUrl() fix has been merged in and up. Travis now green after re-run

**Pull request merged**
