### PR TITLE
Allowing SVGs in the assets directory

### PR DESCRIPTION
**Pull request by nickspiel**
This should be combined with a PR I have started on silverstripe-framework https://github.com/silverstripe/silverstripe-framework/pull/4669

### CODE REVIEW

**Comment by nickspiel** [comment]
Am I able to get some feedback on this? I need it pretty desperately fro a project.

**Comment by stevie-mayhew** [comment]
@nickspiel if you need it for a project you can add it via YML in your own project:

```
File:
  allowed_extensions:
    - svg
```

I am for this being merged, seeing as I just copied that from my current project.

**Comment by nickspiel** [comment]
Yeah in my other PR I had the same advice. Would be nice to have this by default, or even remove the `File` type restrictions entirely.

**Comment by dhensby** [comment]
Thanks

**Pull request merged**
