### PR TITLE
MNT Remove unused email config

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-framework/issues/10097

If CI is red, then re-run after other PRs in linked issue have been merged

### CODE REVIEW

**Review by GuySartorelli — APPROVED** [review]
Merge only when other PRs are ready

**Comment by GuySartorelli** [comment]
@emteknetnz CI on this is failing even after merging the other PRs.

**Comment by emteknetnz** [comment]
@GuySartorelli have created PR to fix https://github.com/silverstripe/silverstripe-behat-extension/pull/229

**Comment by GuySartorelli** [comment]
asset-admin behat is still failing after the linked PR was merged.

**Review by GuySartorelli — APPROVED** [review]
Looks good now

**Pull request merged**
